import math
import random

# File: simulation/thermal_model.py

class ServerHall:
    def __init__(self):
        # Initial Conditions
        self.room_temp = 70.0       # Start at a nice 70°F
        self.ambient_temp = 75.0    # Default "Outside" Temp
        
        # Physics Constants (Tunable)
        self.thermal_mass = 50.0    # How hard is it to change the room temp?
        self.insulation = 0.1       # Heat leak factor (High = Poor Insulation)
        
        # Metrics for the GUI
        self.humidity = 45.0        # % RH
        self.dew_point = 48.0       # °F

    def set_ambient_temp(self, temp_f):
        """
        Updates the external temperature. 
        In your HIL setup, this is driven by the Rigol Frequency.
        """
        # Clamp inputs to realistic Earth temperatures (-40F to 130F)
        self.ambient_temp = max(-40, min(130, temp_f))

    def update(self, load_percent, cooling_percent, dt_seconds):
        """
        Calculates the new room temperature based on:
        1. Heat generated by Servers (Load)
        2. Heat removed by CRAC/CRAH (Cooling)
        3. Heat transfer from Outside (Ambient vs Room Delta)
        """
        
        # 1. HEAT SOURCE: Servers generating heat (0-10 kW equivalent)
        heat_in = (load_percent / 100.0) * 5.0 * dt_seconds
        
        # 2. HEAT SINK: Cooling system removing heat
        # Cooling efficiency drops if we push it too hard (simulated diminishing returns)
        heat_out = (cooling_percent / 100.0) * 8.0 * dt_seconds
        
        # 3. AMBIENT TRANSFER (Newton's Law of Cooling)
        # If Outside > Inside, heat leaks IN.
        # If Outside < Inside, heat leaks OUT.
        delta_t = self.ambient_temp - self.room_temp
        heat_transfer = delta_t * self.insulation * dt_seconds

        # Apply changes to the Room Temperature
        net_heat_change = heat_in - heat_out + heat_transfer
        self.room_temp += net_heat_change / self.thermal_mass

        # Simple Humidity Physics (Hotter air holds more moisture -> Lower RH)
        # This is a simplification, but good enough for a dashboard.
        self.humidity = 45.0 - (self.room_temp - 70.0) * 0.5
        self.dew_point = self.room_temp - ((100 - self.humidity) / 5.0)

    def get_metrics(self):
        return {
            'temp_f': round(self.room_temp, 2),
            'humidity_rh': round(self.humidity, 1),
            'dew_point_f': round(self.dew_point, 1),
            'ambient_f': round(self.ambient_temp, 1) # Added for debug
        }

# --- SELF TEST ---
if __name__ == "__main__":
    hall = ServerHall()
    print("--- SIMULATING 10 SECONDS OF FULL LOAD ---")
    for i in range(10):
        # 100% Load, 50% Cooling
        hall.update(server_load_percent=100, cooling_percent=50) 
        m = hall.get_metrics()
        print(f"Time {i}s: Temp={m['temp_f']}F | RH={m['humidity_rh']}% | DP={m['dew_point_f']}F")